name: telebugs-rails

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby/${{ matrix.ruby }} (Rails ${{ matrix.rails }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ruby: "3.0", rails: "6.1.0" }
          - { ruby: "3.0", rails: "7.0.0" }
          - { ruby: "3.0", rails: "7.1.0" }
          - { ruby: "3.1", rails: "6.1.0" }
          - { ruby: "3.1", rails: "7.0.0" }
          - { ruby: "3.1", rails: "7.1.0" }
          - { ruby: "3.2", rails: "6.1.0" }
          - { ruby: "3.2", rails: "7.0.0" }
          - { ruby: "3.2", rails: "7.1.0" }
          - { ruby: "3.3", rails: "6.1.0" }
          - { ruby: "3.3", rails: "7.0.0" }
          - { ruby: "3.3", rails: "7.1.0" }

    env:
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Run the default task
        run: bundle exec rake
